### PR TITLE
Adds a range validator

### PR DESCRIPTION
**Pull request by julien**
Hey @julien! Looks like an useful validator! Just wondering about the name. Do you think perhaps `.inRange()` would be more clear?

### CODE REVIEW

**Comment by julien** [comment]
Hey @brunobasto, 
Thanks! Yes `.inRange()` seems better. I'll  update that.

**Comment by brunobasto** [comment]
Looks like you figured things on your own 🤣

**Comment by robframpton** [comment]
Rerunning CI.

**Review by robframpton — APPROVED** [review]
LGTM.

**Pull request merged**
