### PR TITLE
Don't attempt to create element in Node.js environment

### PR DESCRIPTION
**Pull request by robframpton**
See https://github.com/metal/metal.js/pull/264

### CODE REVIEW

**Comment by eduardolundgren** [comment]
Can be used `isServerSide` instead?
https://github.com/metal/metal.js/blob/1517926dcc80c9f36966a8464e46535e22dcf69d/packages/metal/src/coreNamed.js#L292

**Comment by robframpton** [comment]
Hey @eduardolundgren, you're right, didn't see we had that helper util. I'll update this branch.

**Comment by robframpton** [comment]
@eduardolundgren, I made the change to both this pull and #264.

**Comment by jbalsas** [comment]
This LGTM, just waiting to clarify our new branching strategy a little bit before merging!

**Pull request merged**
