### PR TITLE
Rename intercept.js

### PR DESCRIPTION
**Pull request by jbalsas**
This PR addresses the issue described in https://github.com/metal/metal.js/issues/228 with blocker extensions and `intercept.js` by renaming it to `IncrementalDomAop.js`, making it consistent at the same time with [SoyAop](https://github.com/metal/metal.js/blob/master/packages/metal-soy/src/SoyAop.js)

### CODE REVIEW

**Review by brunobasto — APPROVED** [review]
LGTM

**Review by robframpton — APPROVED** [review]
LGTM

**Comment by eduardolundgren** [comment]
Camel case files are for classes. This one has no class inside, therefore it needs to be lowercased. Could you guys update? Sorry for catching that later.

**Comment by robframpton** [comment]
https://github.com/metal/metal.js/pull/237

**Pull request merged**
