### PR TITLE
Store property on static STATE object rather than constructor

### PR DESCRIPTION
**Pull request by robframpton**

### CODE REVIEW

**Comment by brunobasto** [comment]
Hey @Robert-Frampton, just out of curiosity, is there an underlying issue that this aims to solve?

**Comment by robframpton** [comment]
Hey @brunobasto 

Yeah, this [original fix](https://github.com/metal/metal.js/commit/9979b997dce6d072da60d6e1e01cc26a0007884d) doesn't work for IE.

I need to look into why the tests I originally added were passing on IE though, I need to update it before we merge this in.

**Comment by brunobasto** [comment]
Gotcha

**Comment by yuchi** [comment]
Reminder: static class properties are not correctly inherited from superclasses in older IE since it doesn't support _setting_ the _[[Prototype]]_ of a function/class.

**Pull request closed without merging**
