### PR TITLE
Improve metal-soy-bundle build

### PR DESCRIPTION
**Pull request by jbalsas**
This is just a simple attempt at making some sense of the build process of `metal-soy-bundle`. I tracked all the pasted snippets to their corresponding `closure-library` and `closure-templates` modules so future diffing is easier.

The `bundle.js` result file is exact to the old one other than some white spaces and it passes all the tests in metal.js.

### CODE REVIEW

**Comment by jbalsas** [comment]
On top of this I have https://github.com/metal/metal.js/commit/c2ab5b0349114567a0de1367dbf618d700719ac9 which should support the new compiler and seems to be backwards compatible. I'm testing right now... fingers crossed!

[Travis Build](https://travis-ci.org/metal/metal.js/builds/215927285)

**Comment by jbalsas** [comment]
Hey guys, I've tested this on several `metal-components` like `metal-treeview` and `metal-datatable` and it seems to work.

@eduardolundgren, @Robert-Frampton, @brunobasto, @fernandosouza, do you have any comments? I'll merge it later today otherwise 😉

**Comment by fernandosouza** [comment]
LGTM @jbalsas.

**Comment by fernandosouza** [comment]
Sorry, I've pushed the wrong button. ^^

**Review by robframpton — APPROVED** [review]

**Comment by jbalsas** [comment]
Just FYI, I've pushed an additional commit ignoring the whole package from linting intents: https://github.com/metal/metal.js/commit/6633b3c68add16fb5cdbf0630d376dff50d8ceba

**Pull request merged**
