### PR TITLE
Makes array.equal a little bit faster in case both arrays point to the same reference

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by eduardolundgren** [comment]
Could you add a test for that?

**Comment by brunobasto** [comment]
It doesn't really change any behavior, other than performance. Not sure how to write a test for that.

**Comment by eduardolundgren** [comment]
It's for coverage purpose.

**Comment by brunobasto** [comment]
@eduardolundgren, that makes total sense. I've added the test. Thx!

**Pull request merged**
