### PR TITLE
Export HTMLParser rather than attaching to window

### PR DESCRIPTION
**Pull request by robframpton**

### CODE REVIEW

**Comment by robframpton** [comment]
I haven't been able to reproduce these test failures locally, not sure what's going on.

**Comment by jbalsas** [comment]
Hey @Robert-Frampton, I'm getting the same error as in Travis if I clean up the project before runing the tests. My steps:

```shell
$ find . -name node_modules -type d -exec rm -rf {} +
$ npm run lerna
$ npm run test
```

**Comment by jbalsas** [comment]
I think you might've failed to commit the [new entry point](https://github.com/metal/metal.js/pull/274/files#diff-bfaf9c11ece89bb7925b2c3c6527fd95R11)?

**Comment by robframpton** [comment]
Strange, I cleaned mine a couple of times and got the same results, but you're right, the entry point didn't get committed :(

**Comment by robframpton** [comment]
Alright, I addressed the merge conflicts and fixed the entry point. Tests are running now.

**Pull request merged**
