### PR TITLE
Update metaljs.com for use with Electric v3.0.0

### PR DESCRIPTION
**Pull request by robframpton**

### CODE REVIEW

**Comment by zenorocha** [comment]
Friendly ping @jbalsas.

**Comment by jbalsas** [comment]
Hey @zenorocha, thanks for the ping! I took a look the other day, but when testing, I saw this in the tutorials section:

screen shot 2018-03-09 at 09 14 45

I haven't had time to take a closer look, though :(

It's likely caused by some marble styling, I guess, so I'm not sure if that affects other places, so we should fix it in general, or just customize on top for this site.

screen shot 2018-03-09 at 09 17 11

**Comment by jbalsas** [comment]
The contribute section was also off, both in this PR and in current Marble, probably since we moved the repos around:

Metal points to an archived repo, and the github icon is not centered, not sure if that's a similar case that with the tutorial links and this affects elsewhere or needs some change? 
screen shot 2018-03-09 at 09 18 57

Marble points to a deleted repo, so it returns a 404
screen shot 2018-03-09 at 09 19 11

**Comment by jbalsas** [comment]
Not from this PR, but worth fixing as well is the description of the tutorials. Otherwise, `asdf` is a good search term 😂 

screen shot 2018-03-09 at 09 24 21

https://github.com/metal/metal.js/blob/master/packages/metaljs.com/src/pages/docs/tutorials/tutorial-todo-jsx/components.md
https://github.com/metal/metal.js/blob/master/packages/metaljs.com/src/pages/docs/tutorials/tutorial-todo-soy/components.md

**Comment by diegonvs** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by diegonvs** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by diegonvs** [comment]
Hey guys, i've continued at #369

**Comment by jbalsas** [comment]
Cool!

**Pull request closed without merging**
